### ISSUE TITLE
wifilight 0.2.0 don"t work with Admin V3.6.2

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.wifilight#16]
host.iobroker | 2019-05-06 09:28:52.060 | error | instance system.adapter.wifilight.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-05-06 09:28:52.060 | error | by controller[0]:     at bootstrap_node.js:625:3
Caught | 2019-05-06 09:28:52.060 | error | by controller[0]:     at startup (bootstrap_node.js:204:16)
Caught | 2019-05-06 09:28:52.060 | error | by controller[0]:     at Function.Module.runMain (module.js:694:10)
Caught | 2019-05-06 09:28:52.060 | error | by controller[0]:     at Function.Module._load (module.js:498:3)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at tryModuleLoad (module.js:506:12)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Module.load (module.js:566:32)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Object.Module._extensions..js (module.js:664:10)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Module._compile (module.js:653:30)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Object. (/opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:20:20)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1148:23)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]: TypeError: fns.adapter is not a function
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:                       ^
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     fns.adapter = fns.adapter(options);
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1148
host.iobroker | 2019-05-06 09:28:51.698 | info | object change system.adapter.wifilight.0
host.iobroker | 2019-05-06 09:28:50.892 | info | Restart adapter system.adapter.wifilight.0 because enabled

**Comment by bouyssic** [comment]
Same problem here. Unfortunately am no good at programing to fix it myself

**Comment by Apollon77** [comment]
Please try "npm i soef"

**Comment by bouyssic** [comment]
Damn I checked the files in my iobroker nodes files and automatically guesses died was installed. I'll check later today and let you know. Thanks

**Comment by bouyssic** [comment]
hello @Apollon77 

I tried what you suggested and unfortunately no change 👎 

````
chris@iobroker:/opt/iobroker$ sudo npm i soef
[sudo] password for chris:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.3 (node_modules/osx-temperature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ soef@0.1.49
updated 1 package and audited 2899 packages in 7.522s
found 58 vulnerabilities (41 low, 1 moderate, 16 high)
  run `npm audit fix` to fix them, or `npm audit` for details
````

**Comment by Chaot1** [comment]
Bei mir erfolgt auch kein Start.
Soef installiert und der "alte" Adapter hat auch funktioniert.
Log:
`

host.ioBroker | 2019-10-31 15:10:06.583 | error | instance system.adapter.wifilight-community.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker | 2019-10-31 15:10:06.583 | error | Caught by controller[0]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
host.ioBroker | 2019-10-31 15:10:06.582 | error | Caught by controller[0]:     at startup (internal/bootstrap/node.js:283:19)
host.ioBroker | 2019-10-31 15:10:06.582 | error | Caught by controller[0]:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
host.ioBroker | 2019-10-31 15:10:06.582 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-10-31 15:10:06.582 | error | Caught by controller[0]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-10-31 15:10:06.582 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-10-31 15:10:06.581 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-10-31 15:10:06.581 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker | 2019-10-31 15:10:06.581 | error | Caught by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:20:20)
host.ioBroker | 2019-10-31 15:10:06.580 | error | Caught by controller[0]:     at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
host.ioBroker | 2019-10-31 15:10:06.580 | error | Caught by controller[0]: TypeError: fns.adapter is not a function
host.ioBroker | 2019-10-31 15:10:06.579 | error | Caught by controller[0]:                       ^
host.ioBroker | 2019-10-31 15:10:06.578 | error | Caught by controller[0]:     fns.adapter = fns.adapter(options);
host.ioBroker | 2019-10-31 15:10:06.577 | error | Caught by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383

`

**Comment by Ilovegym66** [comment]
fixed with 1.1.0
